version: "3.9"
services:
  interest-cal-app:
    container_name: interest-cal
    restart: always
    image: ${IMAGE_NAME}
    ports:
      - 3500:3500
    networks:
      - application
    depends_on:
      - mongodb
    command: ./interest-cal-api

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: sam
      MONGO_INITDB_ROOT_PASSWORD: sam
    volumes:
      - mongodb-data:/data/db
    networks:
      - application

volumes:
  mongodb-data:

networks:
  application: